@startuml usecases
left to right direction

package "Tennis Court" {
  usecase "Update reservable tennis courts" as update
  note right
    - Find reservable tennis courts
    - Save & Notify newly found reservable tennis courts
    - Delete reserved tennis courts
  end note

  usecase "Get all reservable tennis courts" as getAll
}

actor Advandage as app
actor User as user

app --> update

user --> getAll

@enduml
